# Generated by Django 3.2.2 on 2021-05-07 18:31

from django.db import migrations, models
import django.db.models.deletion
import main_clothesmarket.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_clothesmarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='kind_order',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('manufactura', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to=main_clothesmarket.models.Product.get_file_name)),
                ('subphoto1', models.ImageField(upload_to=main_clothesmarket.models.Product.get_file_name)),
                ('subphoto2', models.ImageField(upload_to=main_clothesmarket.models.Product.get_file_name)),
                ('subphoto3', models.ImageField(upload_to=main_clothesmarket.models.Product.get_file_name)),
                ('product_order', models.IntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_clothesmarket.kind')),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
